services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: budgetplanner
      # MYSQL_USER: klu
      # MYSQL_PASSWORD: klu
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql # volume added here
    networks:
    - app-net

  backend:
    container_name: springboot
    build:
      context: ./BudgetPlanner-Backend/BudgetPlanner
      dockerfile: ../../BudgetPlanner-FullStack/backend.Dockerfile
    ports:
      - "2025:1430"
    depends_on:
      - mysqldb
    restart: on-failure
    networks:
      - app-net

  frontend:
    container_name: react
    build:
      context: ./BudgetPlanner-Frontend
      dockerfile: ../BudgetPlanner-FullStack/frontend.Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://backend:2000
    depends_on:
      - backend
    networks:
      - app-net

# Declare volumes at the bottom
volumes:
  mysql-data:

networks:
  app-net:
    driver: bridge